version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_im-message-service
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=im-message-service
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=M25pTceD
      - MYSQL_ADDRESS=10.12.110.146:3306
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-1r6il3p8.sql.tencentcdb.com:22673
networks:
  default:
    external:
      name: wxcb0
